### PR TITLE
example use case via requests package

### PR DESCRIPTION
**Pull request by willfinnigan**
Adds a python file for example requests to use as a test case.

I'm struggling to get this to work and I don't understand why.

### CODE REVIEW

**Comment by willfinnigan** [comment]
```
Traceback (most recent call last):
  File "/Users/willfinnigan/.conda/envs/retrobiohub/lib/python3.9/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/willfinnigan/.conda/envs/retrobiohub/lib/python3.9/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/willfinnigan/.conda/envs/retrobiohub/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/willfinnigan/.conda/envs/retrobiohub/lib/python3.9/site-packages/flask_restx/api.py", line 672, in error_router
    return original_handler(e)
  File "/Users/willfinnigan/.conda/envs/retrobiohub/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/willfinnigan/.conda/envs/retrobiohub/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/willfinnigan/.conda/envs/retrobiohub/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/willfinnigan/.conda/envs/retrobiohub/lib/python3.9/site-packages/flask_restx/api.py", line 672, in error_router
    return original_handler(e)
  File "/Users/willfinnigan/.conda/envs/retrobiohub/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/willfinnigan/.conda/envs/retrobiohub/lib/python3.9/site-packages/flask/app.py", line 1492, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/willfinnigan/.conda/envs/retrobiohub/lib/python3.9/site-packages/flask/app.py", line 1478, in raise_routing_exception
    raise FormDataRoutingRedirect(request)

flask.debughelpers.FormDataRoutingRedirect: b"A request was sent to this URL (http://127.0.0.1:5000/retrobiohub) but a redirect was issued automatically by the routing system to 'http://127.0.0.1:5000/retrobiohub/'.  The URL was defined with a trailing slash so Flask will automatically redirect to the URL with the trailing slash if it was accessed without one.  Make sure to directly send your POST-request to this URL since we can't make browsers or HTTP clients redirect with form data reliably or without user interaction.\n\nNote: this exception is only raised in debug mode"
```

**Comment by willfinnigan** [comment]
Ah didn't like the lack of a trailing /

But now I have a new error...   

```
Traceback (most recent call last):
  File "/Users/willfinnigan/.conda/envs/retrobiohub/lib/python3.9/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/willfinnigan/.conda/envs/retrobiohub/lib/python3.9/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/willfinnigan/.conda/envs/retrobiohub/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/willfinnigan/.conda/envs/retrobiohub/lib/python3.9/site-packages/flask_restx/api.py", line 671, in error_router
    return original_handler(f)
  File "/Users/willfinnigan/.conda/envs/retrobiohub/lib/python3.9/site-packages/flask_restx/api.py", line 669, in error_router
    return self.handle_error(e)
  File "/Users/willfinnigan/.conda/envs/retrobiohub/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/willfinnigan/.conda/envs/retrobiohub/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/willfinnigan/.conda/envs/retrobiohub/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/willfinnigan/.conda/envs/retrobiohub/lib/python3.9/site-packages/flask_restx/api.py", line 671, in error_router
    return original_handler(f)
  File "/Users/willfinnigan/.conda/envs/retrobiohub/lib/python3.9/site-packages/flask_restx/api.py", line 669, in error_router
    return self.handle_error(e)
  File "/Users/willfinnigan/.conda/envs/retrobiohub/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/willfinnigan/.conda/envs/retrobiohub/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/willfinnigan/.conda/envs/retrobiohub/lib/python3.9/site-packages/flask_restx/api.py", line 403, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/willfinnigan/.conda/envs/retrobiohub/lib/python3.9/site-packages/flask/views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "/Users/willfinnigan/.conda/envs/retrobiohub/lib/python3.9/site-packages/flask_restx/resource.py", line 49, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/willfinnigan/PycharmProjects/bch_RetroBioHub/retrobiohub/request.py", line 36, in post
    payload = new.map_reactions_to_enzymes()
  File "/Users/willfinnigan/PycharmProjects/bch_RetroBioHub/retrobiohub/retrobiocat_biocathub_mapper/retrobiocat_biocathub_mapper.py", line 25, in map_reactions_to_enzymes
    for i in self.rbc_model:
TypeError: 'NoneType' object is not iterable
```

**Comment by willfinnigan** [comment]
I can make the post request ok, and printing `self.rbc_model` gives what I think should be the expected result.

As `map_reactions_to_enzymes` iterates over `self.rbc_model`, it hits `reaction = ReactionMapper(i).map_reaction()` and causes this error (I think)..

I think this is an error in the pydantic code but I don't fully understand what this is doing.. 

```
Traceback (most recent call last):
  File "/Users/willfinnigan/.conda/envs/retrobiohub/lib/python3.9/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/willfinnigan/.conda/envs/retrobiohub/lib/python3.9/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/willfinnigan/.conda/envs/retrobiohub/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/willfinnigan/.conda/envs/retrobiohub/lib/python3.9/site-packages/flask_restx/api.py", line 671, in error_router
    return original_handler(f)
  File "/Users/willfinnigan/.conda/envs/retrobiohub/lib/python3.9/site-packages/flask_restx/api.py", line 669, in error_router
    return self.handle_error(e)
  File "/Users/willfinnigan/.conda/envs/retrobiohub/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/willfinnigan/.conda/envs/retrobiohub/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/willfinnigan/.conda/envs/retrobiohub/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/willfinnigan/.conda/envs/retrobiohub/lib/python3.9/site-packages/flask_restx/api.py", line 671, in error_router
    return original_handler(f)
  File "/Users/willfinnigan/.conda/envs/retrobiohub/lib/python3.9/site-packages/flask_restx/api.py", line 669, in error_router
    return self.handle_error(e)
  File "/Users/willfinnigan/.conda/envs/retrobiohub/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/willfinnigan/.conda/envs/retrobiohub/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/willfinnigan/.conda/envs/retrobiohub/lib/python3.9/site-packages/flask_restx/api.py", line 403, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/willfinnigan/.conda/envs/retrobiohub/lib/python3.9/site-packages/flask/views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "/Users/willfinnigan/.conda/envs/retrobiohub/lib/python3.9/site-packages/flask_restx/resource.py", line 49, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/willfinnigan/PycharmProjects/bch_RetroBioHub/retrobiohub/request.py", line 36, in post
    payload = new.map_reactions_to_enzymes()
  File "/Users/willfinnigan/PycharmProjects/bch_RetroBioHub/retrobiohub/retrobiocat_biocathub_mapper/retrobiocat_biocathub_mapper.py", line 26, in map_reactions_to_enzymes
    reaction = ReactionMapper(i).map_reaction()
  File "/Users/willfinnigan/PycharmProjects/bch_RetroBioHub/retrobiohub/retrobiocat_biocathub_mapper/mapper_functions.py", line 51, in map_reaction
    new = Reaction.from_orm(Reactioncls(self.rbc_model["reaction"],self.map_reactants(), self.map_products()))
  File "/Users/willfinnigan/PycharmProjects/bch_RetroBioHub/retrobiohub/retrobiocat_biocathub_mapper/mapper_functions.py", line 33, in map_reactants
    new = Reactant.from_orm(Reactantcls("substrate", i, iupac))
  File "/Users/willfinnigan/.conda/envs/retrobiohub/lib/python3.9/site-packages/pydantic/main.py", line 631, in from_orm
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for Reactant
name
  none is not an allowed value (type=type_error.none.not_allowed)

```

**Comment by StephanM87** [comment]
## Problem was the pubchem adapter

I have tested your code and the problem seemed to be the pubchem adatper. On requesting a iupac name based on a SMILES, it returned none. Pydantic triggered an exception.

I tested your script on my system and it worked

I have added a small workaround but this will be the first subpackage to work on!

**Pull request merged**
